# Generated by Django 5.2.15 on 2026-07-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'color', 'color_shade'), name='unique_product_variant'),
        ),
    ]
