# Generated by Django 5.2.15 on 2026-07-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_unique_product_variant'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='store_produ_categor_92f296_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['color'], name='store_produ_color_4b4fa3_idx'),
        ),
    ]
